name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile Slides
      uses: xu-cheng/latex-action@master
      with:
        root_file: ou-tma.ins
    - name: Compile Example
      uses: xu-cheng/latex-action@master
      with:
        root_file: ou-tma.dtx
        working_directory: example
    - name: Check pdf files
      run: |
        file ou-tma.pdf | grep -q ' PDF '
        file ou-tma.sty | grep -q ' STY '
        file ou-tma-sup.sty | grep -q ' STY '
    - name: Upload pdf + sty
      run: |
        # configure git
        git config --global user.name "Geoff Bot"
        git config --global user.email "geoff.bot@adaso.com"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:GeoffRiley/tma.git "$GITHUB_WORKSPACE/deploy"
        cp -f ou-tma.pdf "$GITHUB_WORKSPACE/deploy/ou-tma.pdf"
        cp -f ou-tma.sty "$GITHUB_WORKSPACE/deploy/ou-tma.sty"
        cp -f ou-tma-sup.sty "$GITHUB_WORKSPACE/deploy/ou-tma-sup.sty"
        cd "$GITHUB_WORKSPACE/deploy"
        git add ou-tma.pdf ou-tma.sty ou-tma-sup.sty
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}